services:
  db:
    image: postgres:13.9-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  selenium_chrome:
    image: selenium/standalone-chrome:112.0-20230421
    shm_size: 2gb
    logging:
      driver: none
#    volumes:
#      - /dev/shm:/dev/shm
    ports:
      - 5900:5900

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      SELENIUM_REMOTE_URL: ${SELENIUM_REMOTE_URL}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      RAILS_ENV: ${RAILS_ENV}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    volumes:
      - .:/rails
    ports:
      - ${WEB_PORT:-3001}:3000
    depends_on:
      - db
      - selenium_chrome

  adminer:
    image: adminer:4.8.1
    ports:
      - ${ADMINER_PORT:-8080}:8080

volumes:
  postgres_data: null