services:
  web:
    build:
      context: .
      dockerfile: "Dockerfile.development"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - ${WEB_PORT:-3001}:3000
    depends_on:
      - db
      - selenium_chrome

  selenium_chrome:
    image: selenium/standalone-chrome:112.0-20230421
    shm_size: 2gb
    logging:
      driver: none
#    volumes:
#      - /dev/shm:/dev/shm
    ports:
      - 5900:5900

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - ${MAILCATCHER_PORT:-1080}:1080

  adminer:
    image: adminer:4.8.1
    ports:
      - ${ADMINER_PORT:-8080}:8080
