services:
  web:
    build:
      context: .
      dockerfile: "Dockerfile.production"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - ${WEB_PORT:-3001}:3000
    depends_on:
      - db
